# Created using wingetcreate 1.12.13.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.12.0.schema.json

PackageIdentifier: PROLOGIC.SBiz
PackageVersion: 6.0.0
PackageLocale: en-US
Publisher: PROLOGIC
PublisherSupportUrl: https://www.facebook.com/ProLogicSoftware/
PrivacyUrl: https://github.com/MozartCarver/SBizV6_Release/releases/tag/PROLOGIC
Author: Mozart Carver
PackageName: SilveredBusiness
License: MIT License
ShortDescription: To make your business life better.
Description: For SME whole sales and retail shop pos + accounting windows bases client/server software.
Tags:
- '#PROLOGIC #SBiz #V6'
ReleaseNotes: First Release for Winget (Terminal Command Line Install)
InstallationNotes: Just install
ManifestType: defaultLocale
ManifestVersion: 1.12.0
